services:
  python:
    image: kennethreitz/pipenv
    volumes:
      - ./:/app:cached
    command: "tail -f /dev/null"
  db:
    image: postgres
    ports:
    - 6666:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust