services:
  python:
    build:
      context: docker/python
    volumes:
      - ./:/app:cached
  db:
    image: postgres
    ports:
    - 6666:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust